# Generated by Django 5.2.14 on 2026-05-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_phone_number_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_spent_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
