# Generated by Django 5.2.14 on 2026-05-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_listing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_logo', models.ImageField(upload_to='bank_logos/')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_tenure', models.IntegerField(help_text='Max tenure in years')),
                ('disbursement_days', models.IntegerField(help_text='Days for loan disbursement')),
                ('cash_reward', models.IntegerField(default=0)),
                ('is_recommended', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'bank_name'],
            },
        ),
    ]
