# Generated by Django 5.2.14 on 2026-05-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_bankoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankoffer',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
