# Generated by Django 5.2.14 on 2026-05-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_builder_property_builder'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='age_of_property',
            field=models.PositiveIntegerField(default=0, help_text='Age in years'),
        ),
        migrations.AddField(
            model_name='property',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='property_brochures/'),
        ),
        migrations.AddField(
            model_name='property',
            name='facing',
            field=models.CharField(blank=True, choices=[('east', 'East'), ('west', 'West'), ('north', 'North'), ('south', 'South'), ('north_east', 'North-East'), ('north_west', 'North-West'), ('south_east', 'South-East'), ('south_west', 'South-West')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='property_floor_plans/'),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi-furnished', 'Semi-furnished'), ('fully-furnished', 'Fully-furnished')], default='unfurnished', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_type',
            field=models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('power_of_attorney', 'Power of Attorney'), ('co_operative_society', 'Co-operative Society')], default='freehold', max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='possession_status',
            field=models.CharField(choices=[('ready_to_move', 'Ready to Move'), ('under_construction', 'Under Construction')], default='ready_to_move', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='posted_by',
            field=models.CharField(choices=[('owner', 'Owner'), ('agent', 'Agent'), ('builder', 'Builder')], default='owner', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='rera_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='rera_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
    ]
